[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
cid = { default-features = true, version = "0.11.1" }
ipfs-unixfs = { version = "0.2.0", default-features = false }
serde = { version = "1.0", features = ["alloc", "derive"] }
serde_json = "1.0.122"
json = "0.12"
